In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import linear_model

In [3]:
kpdl_data = pd.read_csv("C:/Users/Admin/Downloads/KOLTEPATIL.BO.csv")
kpdl_data

Date        Open        High         Low       Close   Adj Close  \
0     2013-09-23   64.050003   65.500000   61.599998   62.150002   58.127819   
1     2013-09-24   62.150002   62.549999   60.250000   61.400002   57.426353   
2     2013-09-25   61.500000   66.750000   60.799999   64.000000   59.858086   
3     2013-09-26   63.700001   66.000000   63.049999   64.199997   60.045143   
4     2013-09-27   64.099998   67.500000   63.549999   65.400002   61.167480   
...          ...         ...         ...         ...         ...         ...   
2463  2023-09-14  455.049988  465.850006  450.000000  454.950012  454.950012   
2464  2023-09-15  461.950012  461.950012  446.200012  456.049988  456.049988   
2465  2023-09-18  458.100006  458.100006  439.799988  443.850006  443.850006   
2466  2023-09-20  440.049988  443.500000  428.250000  433.399994  433.399994   
2467  2023-09-21  435.049988  438.000000  426.000000  434.850006  434.850006   

        Volume  
0      31801.0  
1      45349.0  
2     111210.0  
3      66809.0  
4      78111.0  
...        ...  
2463   13522.0  
2464   12991.0  
2465   21202.0  
2466   24868.0  
2467    7397.0  

[2468 rows x 7 columns]

In [4]:
np.where(pd.isnull(kpdl_data))

(array([ 123,  123,  123,  123,  123,  123,  144,  144,  144,  144,  144,
         144,  261,  261,  261,  261,  261,  261,  352,  352,  352,  352,
         352,  352, 1078, 1078, 1078, 1078, 1078, 1078, 1095, 1095, 1095,
        1095, 1095, 1095, 1096, 1096, 1096, 1096, 1096, 1096, 1656, 1656,
        1656, 1656, 1656, 1656, 1666, 1666, 1666, 1666, 1666, 1666, 2070,
        2070, 2070, 2070, 2070, 2070, 2121, 2121, 2121, 2121, 2121, 2121,
        2380, 2380, 2380, 2380, 2380, 2380, 2387, 2387, 2387, 2387, 2387,
        2387, 2411, 2411, 2411, 2411, 2411, 2411, 2412, 2412, 2412, 2412,
        2412, 2412, 2413, 2413, 2413, 2413, 2413, 2413, 2414, 2414, 2414,
        2414, 2414, 2414, 2417, 2417, 2417, 2417, 2417, 2417, 2418, 2418,
        2418, 2418, 2418, 2418, 2419, 2419, 2419, 2419, 2419, 2419, 2422,
        2422, 2422, 2422, 2422, 2422, 2427, 2427, 2427, 2427, 2427, 2427,
        2429, 2429, 2429, 2429, 2429, 2429, 2431, 2431, 2431, 2431, 2431,
        2431, 2432, 2432, 2432, 2432, 

In [5]:
kpdl_data_2 = kpdl_data.dropna()
kpdl_data_2

Date        Open        High         Low       Close   Adj Close  \
0     2013-09-23   64.050003   65.500000   61.599998   62.150002   58.127819   
1     2013-09-24   62.150002   62.549999   60.250000   61.400002   57.426353   
2     2013-09-25   61.500000   66.750000   60.799999   64.000000   59.858086   
3     2013-09-26   63.700001   66.000000   63.049999   64.199997   60.045143   
4     2013-09-27   64.099998   67.500000   63.549999   65.400002   61.167480   
...          ...         ...         ...         ...         ...         ...   
2463  2023-09-14  455.049988  465.850006  450.000000  454.950012  454.950012   
2464  2023-09-15  461.950012  461.950012  446.200012  456.049988  456.049988   
2465  2023-09-18  458.100006  458.100006  439.799988  443.850006  443.850006   
2466  2023-09-20  440.049988  443.500000  428.250000  433.399994  433.399994   
2467  2023-09-21  435.049988  438.000000  426.000000  434.850006  434.850006   

        Volume  
0      31801.0  
1      45349.0  
2     111210.0  
3      66809.0  
4      78111.0  
...        ...  
2463   13522.0  
2464   12991.0  
2465   21202.0  
2466   24868.0  
2467    7397.0  

[2442 rows x 7 columns]

In [6]:
np.where(pd.isnull(kpdl_data_2))

(array([], dtype=int64), array([], dtype=int64))

In [7]:
X = kpdl_data_2.iloc[: , 1:4]
X

Open        High         Low
0      64.050003   65.500000   61.599998
1      62.150002   62.549999   60.250000
2      61.500000   66.750000   60.799999
3      63.700001   66.000000   63.049999
4      64.099998   67.500000   63.549999
...          ...         ...         ...
2463  455.049988  465.850006  450.000000
2464  461.950012  461.950012  446.200012
2465  458.100006  458.100006  439.799988
2466  440.049988  443.500000  428.250000
2467  435.049988  438.000000  426.000000

[2442 rows x 3 columns]

In [8]:
y = kpdl_data_2.iloc[: , 4]
y

0        62.150002
1        61.400002
2        64.000000
3        64.199997
4        65.400002
           ...    
2463    454.950012
2464    456.049988
2465    443.850006
2466    433.399994
2467    434.850006
Name: Close, Length: 2442, dtype: float64

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [10]:
X_train

Open        High         Low
782    99.000000   99.849998   98.449997
76     85.349998   87.000000   84.150002
192   151.800003  156.899994  151.800003
976   207.600006  208.750000  192.850006
208   155.149994  167.000000  154.199997
...          ...         ...         ...
964   161.149994  164.399994  158.500000
909   181.899994  183.449997  179.000000
1103  330.049988  342.000000  325.950012
237   179.899994  181.699997  176.199997
1065  371.000000  385.350006  362.250000

[1953 rows x 3 columns]

In [11]:
MLR = linear_model.LinearRegression().fit(X_train, y_train)

In [12]:
y_pred = MLR.predict(X_test)
len(y_pred)

489

In [13]:
a = pd.DataFrame(y_pred)

In [14]:
len(X_test)

489

In [46]:
latest_values = [439.50, 457.10, 433.40]
lv_array = np.array(latest_values)

In [52]:
b = lv_array.reshape(1, -1)
b


array([[439.5, 457.1, 433.4]])

In [54]:
latest_close_predicted = MLR.predict(b)
latest_close_predicted

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([445.79193622])

In [17]:
error = abs(436.85-441.64)/436.85
error

0.010964862080805684

In [15]:
latest_values = [442, 453, 433]
lv_array = np.array(latest_values)
b = lv_array.reshape(1, -1)
b


array([[442, 453, 433]])

In [16]:
latest_close_predicted = MLR.predict(b)
latest_close_predicted

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([441.64701092])