# Building a layer

We are going to use some part of code that we used earlier (Building a neuron) and are going to build up on that.

Note: As we are using Np.random, your outputs might differ from me and the outputs here might differ from the last code.

In [1]:
import numpy as np

In [2]:
inputs = np.random.rand(5)

In [3]:
weights = np.random.rand(5)

In [6]:
bias = np.random.randint(1,10)

In [7]:
inputs, weights, bias

(array([0.67567113, 0.69008096, 0.94906868, 0.71968291, 0.73165738]),
 array([0.65799994, 0.98663877, 0.50991922, 0.81919326, 0.23486747]),
 6)

In [9]:
outputs = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + inputs[4]*weights[4] + bias
outputs

8.370802464517734

So if Our layer consists of 4 such neurons then it will have 4 such weights and 4 biases for each neuron.

In [11]:
weights1 = np.random.rand(5)
weights2 = np.random.rand(5)
weights3 = np.random.rand(5)
weights4 = np.random.rand(5)
weights1, weights2, weights3, weights4

(array([0.81348188, 0.5764507 , 0.50295362, 0.13261031, 0.58376379]),
 array([0.63404978, 0.80589292, 0.12628487, 0.69934624, 0.29426151]),
 array([0.31751659, 0.44074705, 0.30782757, 0.83365578, 0.64382636]),
 array([0.87391208, 0.28516335, 0.28867559, 0.1454441 , 0.0069981 ]))

In [14]:
bias1 = np.random.randint(1,10)
bias2 = np.random.randint(0,5)
bias3 = np.random.randint(-2,7)
bias4 = np.random.randint(3,14)
bias1, bias2, bias3, bias4

(3, 2, 4, 3)

So now we have 5 inputs which will be going to each neuron, 5 weights per neuron and a bias

In [16]:
output_eachneuron = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + inputs[4]*weights1[4] + bias1, inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + inputs[4]*weights2[4] + bias2, inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + inputs[4]*weights3[4] + bias3, inputs[0]*weights4[0] + inputs[1]*weights4[1] + inputs[2]*weights4[2] + inputs[3]*weights4[3] + inputs[4]*weights4[4] + bias4]
output_eachneuron

[4.947333863987419, 3.822999657427269, 5.8818655723522735, 4.171029766333031]

So now we have calculated output of each neuron within our layer, We had 4 neurons in the layer so each neuron will have it's individual output